[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3
startCommand = "npm run start"

[env]
NODE_ENV = { default = "production" }
PORT = { default = "3000" }
API_PORT = { default = "3001" }

# Database
DATABASE_PATH = { default = "/app/data/market_caps.db" }

# Logging
LOG_LEVEL = { default = "info" }

# Data collection schedule
DAILY_COLLECTION_ENABLED = { default = "true" }
DAILY_COLLECTION_TIME = { default = "18" }
WEEKLY_FUNDAMENTALS_DAY = { default = "0" }

# Rate limiting
MAX_REQUESTS_PER_MINUTE = { default = "100" }

# Next.js
NEXT_TELEMETRY_DISABLED = { default = "1" }

[experimental]
nixpacksPlan = "node"